
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  description: Production applications
  
  sourceRepos:
  - https://github.com/your-org/cloudtrade-platform.git
  
  destinations:
  - namespace: 'cloudtrade-*'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  roles:
  - name: admin
    description: Admin privileges
    policies:
    - p, proj:production:admin, applications, *, production/*, allow
    groups:
    - cloudtrade-admins
  
  - name: developer
    description: Read-only access
    policies:
    - p, proj:production:developer, applications, get, production/*, allow
    groups:
    - cloudtrade-developers
